-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 20:28:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_reservas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_reservas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_reservas` DEFAULT CHARACTER SET utf8 ;
USE `db_reservas` ;

-- -----------------------------------------------------
-- Table `db_reservas`.`tbl_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reservas`.`tbl_genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reservas`.`tbl_tipodocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reservas`.`tbl_tipodocumento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reservas`.`tbl_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reservas`.`tbl_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_documento` VARCHAR(12) NULL,
  `apellido_paterno` VARCHAR(100) NULL,
  `apellido_materno` VARCHAR(100) NULL,
  `nombres` VARCHAR(100) NULL,
  `celular` VARCHAR(15) NULL,
  `correo` VARCHAR(50) NULL,
  `fecha_nacimiento` DATE NULL,
  `genero_id` INT NOT NULL,
  `tipodocumento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_cliente_tbl_genero`
    FOREIGN KEY (`genero_id`)
    REFERENCES `db_reservas`.`tbl_genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_cliente_tbl_tipodocumento1`
    FOREIGN KEY (`tipodocumento_id`)
    REFERENCES `db_reservas`.`tbl_tipodocumento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reservas`.`tbl_hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reservas`.`tbl_hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NOT NULL,
  `numero_habitaciones` INT NULL,
  `direccion` VARCHAR(100) NULL,
  `telefono` VARCHAR(15) NULL,
  `imagen` VARCHAR(500) NULL,
  `descripcion` LONGTEXT NULL,
  `calificacion` INT NULL,
  `localizacion` VARCHAR(500) NULL,
  `precio_minimo` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reservas`.`tbl_tipohabitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reservas`.`tbl_tipohabitacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `precio` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reservas`.`tbl_habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reservas`.`tbl_habitacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `estado` TINYINT NULL,
  `hotel_id` INT NOT NULL,
  `tipohabitacion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_habitacion_tbl_hotel1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `db_reservas`.`tbl_hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_habitacion_tbl_tipohabitacion1`
    FOREIGN KEY (`tipohabitacion_id`)
    REFERENCES `db_reservas`.`tbl_tipohabitacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reservas`.`tbl_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reservas`.`tbl_reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_reserva` DATE NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `estado` TINYINT NULL,
  `precio_total` DOUBLE NULL,
  `cliente_id` INT NOT NULL,
  `hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_reserva_tbl_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `db_reservas`.`tbl_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_reserva_tbl_hotel1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `db_reservas`.`tbl_hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reservas`.`tbl_reservadetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reservas`.`tbl_reservadetalle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reserva_id` INT NOT NULL,
  `habitacion_id` INT NOT NULL,
  `precio` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `subtotal` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_reservadetalle_tbl_reserva1`
    FOREIGN KEY (`reserva_id`)
    REFERENCES `db_reservas`.`tbl_reserva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_reservadetalle_tbl_habitacion1`
    FOREIGN KEY (`habitacion_id`)
    REFERENCES `db_reservas`.`tbl_habitacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
